// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var app;

  app = (function() {
    app = {};
    app.init = function() {
      return this.scream();
    };
    return app.scream = function() {
      return console.log('Yo!');
    };
  })();

}).call(this);
